"""ajout de la colonne cretaed_by dans la table organization

Revision ID: 1540c4deb930
Revises: 08cc080ccdd2
Create Date: 2026-02-23 12:10:18.918908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1540c4deb930'
down_revision: Union[str, Sequence[str], None] = '08cc080ccdd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'organizations', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'created_by')
    # ### end Alembic commands ###
