"""ajout des relations entre les tables organizations, organizations_members and users

Revision ID: 24002044a3ee
Revises: 3fc142847495
Create Date: 2026-02-24 01:07:18.706633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24002044a3ee'
down_revision: Union[str, Sequence[str], None] = '3fc142847495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
