"""j'avais oublié user dans les relations org, org_member et user

Revision ID: 3fc142847495
Revises: 7645f7a357dd
Create Date: 2026-02-23 17:19:35.676366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc142847495'
down_revision: Union[str, Sequence[str], None] = '7645f7a357dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
