"""ajout des relations entre les tables organizations, organizations_members and users

Revision ID: 7645f7a357dd
Revises: 1540c4deb930
Create Date: 2026-02-23 17:08:53.110302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7645f7a357dd'
down_revision: Union[str, Sequence[str], None] = '1540c4deb930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
